name: Run stresser
on: workflow_dispatch
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - run: |
          ping -c 2 -6 2606:4700:4700::1111 >/dev/null 2>&1 && echo "✅ ДОСТУП ЕСТЬ: хостер дал IPv6, интернет работает." || echo "❌ ДОСТУПА НЕТ: IPv6 не выдан или не настроен."
